# This is a basic workflow to help you get started with Actions

name: My-Github-action-Basics
env:
  APPLICATION_NAME: "MyFlask"
  PACKAGE_NAME: "flask-deploy-ver-${{ github.sha }}"

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch  
  push:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  my_testing:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world from Testing!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          pwd
          ls -la
          
  my_deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
<<<<<<< HEAD

=======
    needs: [my_testing]
>>>>>>> 38ae9d078a6a9c70ef9d5614fc088dca9c77c849
    
    steps:

      - name: Print Hello World!
        run: echo Hello World from Deploy!  
